export const DEPARTMENTS = 'DEPARTAMENTOS';
export const STUDENTS = 'ESTUDIANTES';
export const COURSES = 'CURSOS';
export const ENROLLMENTS = 'MATRICULAS';

export const ALL_TABLES = [DEPARTMENTS, STUDENTS, COURSES, ENROLLMENTS]